### ISSUE TITLE
I removed you from the maintainers team

### ISSUE THREAD

**Issue by FichteFoll** [packagecontrol/pygments#1]
Hi @AndreasBackx, just a quick update that I removed you from the maintainers team due to a restructuring of permissions on this organization. You will still have admin permissions on this repo and any other you create, but you won't have write access to the other repositories.

I'm not sure if you received an email about this change, but I wanted to clear up potential confusion. You didn't specify an email address on your profile, so I chose to open an issue instead.

**Comment by AndreasBackx** [comment]
That's fine, don't worry. I'm not even using ST3 anymore these days. Thank you for the update.
